apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: user-service-db-creds
  namespace: blog
spec:
  vaultAuthRef: user-service-vault-auth
  mount: database
  path: creds/user-service
  renewalPercent: 67
  destination:
    name: user-service-db-creds
    create: true
    transformation:
      templates:
        DATABASE_URL:
          text: "postgresql://{{.Secrets.username}}:{{.Secrets.password}}@postgres:5432/blog_users"
  rolloutRestartTargets:
    - kind: Deployment
      name: user-service
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: post-service-db-creds
  namespace: blog
spec:
  vaultAuthRef: post-service-vault-auth
  mount: database
  path: creds/post-service
  renewalPercent: 67
  destination:
    name: post-service-db-creds
    create: true
    transformation:
      templates:
        DATABASE_URL:
          text: "postgresql://{{.Secrets.username}}:{{.Secrets.password}}@postgres:5432/blog_posts"
  rolloutRestartTargets:
    - kind: Deployment
      name: post-service
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: comment-service-db-creds
  namespace: blog
spec:
  vaultAuthRef: comment-service-vault-auth
  mount: database
  path: creds/comment-service
  renewalPercent: 67
  destination:
    name: comment-service-db-creds
    create: true
    transformation:
      templates:
        DATABASE_URL:
          text: "postgresql://{{.Secrets.username}}:{{.Secrets.password}}@postgres:5432/blog_comments"
  rolloutRestartTargets:
    - kind: Deployment
      name: comment-service
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: notification-service-db-creds
  namespace: blog
spec:
  vaultAuthRef: notification-service-vault-auth
  mount: database
  path: creds/notification-service
  renewalPercent: 67
  destination:
    name: notification-service-db-creds
    create: true
    transformation:
      templates:
        DATABASE_URL:
          text: "postgresql://{{.Secrets.username}}:{{.Secrets.password}}@postgres:5432/blog_notifications"
  rolloutRestartTargets:
    - kind: Deployment
      name: notification-service
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: media-service-db-creds
  namespace: blog
spec:
  vaultAuthRef: media-service-vault-auth
  mount: database
  path: creds/media-service
  renewalPercent: 67
  destination:
    name: media-service-db-creds
    create: true
    transformation:
      templates:
        DATABASE_URL:
          text: "postgresql://{{.Secrets.username}}:{{.Secrets.password}}@postgres:5432/blog_media"
  rolloutRestartTargets:
    - kind: Deployment
      name: media-service
