apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: auth-service-nats-creds
  namespace: blog
spec:
  vaultAuthRef: auth-service-vault-auth
  mount: secret
  type: kv-v2
  path: blog/nats/auth-service
  refreshAfter: 300s
  destination:
    name: auth-service-nats-creds
    create: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: user-service-nats-creds
  namespace: blog
spec:
  vaultAuthRef: user-service-vault-auth
  mount: secret
  type: kv-v2
  path: blog/nats/user-service
  refreshAfter: 300s
  destination:
    name: user-service-nats-creds
    create: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: post-service-nats-creds
  namespace: blog
spec:
  vaultAuthRef: post-service-vault-auth
  mount: secret
  type: kv-v2
  path: blog/nats/post-service
  refreshAfter: 300s
  destination:
    name: post-service-nats-creds
    create: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: comment-service-nats-creds
  namespace: blog
spec:
  vaultAuthRef: comment-service-vault-auth
  mount: secret
  type: kv-v2
  path: blog/nats/comment-service
  refreshAfter: 300s
  destination:
    name: comment-service-nats-creds
    create: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: notification-service-nats-creds
  namespace: blog
spec:
  vaultAuthRef: notification-service-vault-auth
  mount: secret
  type: kv-v2
  path: blog/nats/notification-service
  refreshAfter: 300s
  destination:
    name: notification-service-nats-creds
    create: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: search-indexer-nats-creds
  namespace: blog
spec:
  vaultAuthRef: search-indexer-vault-auth
  mount: secret
  type: kv-v2
  path: blog/nats/search-indexer
  refreshAfter: 300s
  destination:
    name: search-indexer-nats-creds
    create: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: media-service-nats-creds
  namespace: blog
spec:
  vaultAuthRef: media-service-vault-auth
  mount: secret
  type: kv-v2
  path: blog/nats/media-service
  refreshAfter: 300s
  destination:
    name: media-service-nats-creds
    create: true
