apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: blog-shared-secrets
  namespace: blog
spec:
  vaultAuthRef: captcha-service-vault-auth
  mount: secret
  type: kv-v2
  path: blog/shared
  refreshAfter: 300s
  destination:
    name: blog-shared-secrets
    create: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: blog-admin-secrets
  namespace: blog
spec:
  vaultAuthRef: auth-service-vault-auth
  mount: secret
  type: kv-v2
  path: blog/admin
  refreshAfter: 300s
  destination:
    name: blog-admin-secrets
    create: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: blog-postgres-secrets
  namespace: blog
spec:
  vaultAuthRef: postgres-vault-auth
  mount: secret
  type: kv-v2
  path: blog/postgres
  refreshAfter: 300s
  destination:
    name: blog-postgres-secrets
    create: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: blog-rsa-key
  namespace: blog
spec:
  vaultAuthRef: auth-service-vault-auth
  mount: secret
  type: kv-v2
  path: blog/rsa-key
  refreshAfter: 300s
  destination:
    name: blog-rsa-key
    create: true
