apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: blog-routes
  namespace: blog
spec:
  http:
    - match:
        - uri:
            prefix: /api/auth/
      corsPolicy:
        allowOrigins:
          - exact: "https://blog.example.com"
    - match:
        - uri:
            prefix: /api/captcha/
      corsPolicy:
        allowOrigins:
          - exact: "https://blog.example.com"
    - match:
        - uri:
            prefix: /api/search
      corsPolicy:
        allowOrigins:
          - exact: "https://blog.example.com"
    - match:
        - uri:
            prefix: /api/comments/posts/
      corsPolicy:
        allowOrigins:
          - exact: "https://blog.example.com"
    - match:
        - uri:
            prefix: /api/comments
      corsPolicy:
        allowOrigins:
          - exact: "https://blog.example.com"
    - match:
        - uri:
            prefix: /api/posts
      corsPolicy:
        allowOrigins:
          - exact: "https://blog.example.com"
    - match:
        - uri:
            prefix: /api/users
      corsPolicy:
        allowOrigins:
          - exact: "https://blog.example.com"
    - match:
        - uri:
            prefix: /api/notifications
      corsPolicy:
        allowOrigins:
          - exact: "https://blog.example.com"
    - match:
        - uri:
            prefix: /api/media
      corsPolicy:
        allowOrigins:
          - exact: "https://blog.example.com"
