apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault-connection
  namespace: blog
spec:
  address: https://vault.production.example.com
  caCertSecretRef: vault-ca-cert
