apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-config
  namespace: blog
data:
  NATS_URL: "nats://nats:4222"
  USER_SERVICE_URL: "http://user-service:3001"
  POST_SERVICE_URL: "http://post-service:3002"
  COMMENT_SERVICE_URL: "http://comment-service:3003"
  NOTIFICATION_SERVICE_URL: "http://notification-service:3004"
  SEARCH_SERVICE_URL: "http://search-service:3005"
  MEDIA_SERVICE_URL: "http://media-service:3006"
  CAPTCHA_SERVICE_URL: "http://captcha-service:3008"
  CORS_ORIGINS: "http://localhost:3007"
  LOG_LEVEL: "info"
