apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blog

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - ingress.yaml
  - postgres/statefulset.yaml
  - nats/deployment.yaml
  - gateway/deployment.yaml
  - user/deployment.yaml
  - post/deployment.yaml
  - comment/deployment.yaml
  - notification/deployment.yaml
  - search/deployment.yaml
  - media/deployment.yaml
  - captcha/deployment.yaml
  - frontend/deployment.yaml
