apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blog

resources:
  - namespace.yaml
  - configmap.yaml
  - service-accounts.yaml
  - postgres/statefulset.yaml
  - nats/deployment.yaml
  - gateway/deployment.yaml
  - user/deployment.yaml
  - post/deployment.yaml
  - comment/deployment.yaml
  - notification/deployment.yaml
  - search/deployment.yaml
  - media/deployment.yaml
  - captcha/deployment.yaml
  - frontend/deployment.yaml
  - istio/gateway.yaml
  - istio/virtual-service.yaml
  - istio/peer-authentication.yaml
  - istio/authorization-policies.yaml
  - istio/destination-rules.yaml
  - vault/vault-connection.yaml
  - vault/vault-auth.yaml
  - vault/static-secrets.yaml
  - vault/dynamic-secrets.yaml
  - vault/nats-secrets.yaml
