apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway
  namespace: blog
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-service
  namespace: blog
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: post-service
  namespace: blog
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: comment-service
  namespace: blog
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service
  namespace: blog
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: search-indexer
  namespace: blog
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: search-query
  namespace: blog
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: media-service
  namespace: blog
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: captcha-service
  namespace: blog
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: blog
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats
  namespace: blog
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  namespace: blog
